/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.extendDirty.lv;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public interface ExtendDirtyLVPNL {
    public static final String _DN = "extendDirtyLV".intern();

    public static interface AccountPNL {
        /**
         * Name of "Account" entity. 
         */
        public static final String __ = "Account".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property. 
         * type: String. 
         * column: "gui". 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "emailAddress" property. 
         * type: String. 
         * column: "email_address". 
         */
        public static final String EMAIL_ADDRESS = (__ + ".emailAddress").intern();

        /**
         * Name of "firstName" property. 
         * type: String. 
         * column: "first_name". 
         */
        public static final String FIRST_NAME = (__ + ".firstName").intern();

        /**
         * Name of "middleName" property. 
         * type: String. 
         * column: "middle_name". 
         */
        public static final String MIDDLE_NAME = (__ + ".middleName").intern();

        /**
         * Name of "lastName" property. 
         * type: String. 
         * column: "last_name". 
         */
        public static final String LAST_NAME = (__ + ".lastName").intern();

        /**
         * Name of "birthDate" property. 
         * type: Timestamp. 
         * column: "birth_date". 
         */
        public static final String BIRTH_DATE = (__ + ".birthDate").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "contact" property. 
         * type: com.landawn.abacus.entity.extendDirty.lv.AccountContact. 
         * column: "AccountContact". 
         */
        public static final String CONTACT = (__ + ".contact").intern();

        /**
         * Name of "devices" property. 
         * type: List<com.landawn.abacus.entity.extendDirty.lv.AccountDevice>. 
         * column: "AccountDevice". 
         */
        public static final String DEVICES = (__ + ".devices").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, EMAIL_ADDRESS, FIRST_NAME, MIDDLE_NAME, LAST_NAME, BIRTH_DATE, STATUS, LAST_UPDATE_TIME, CREATE_TIME, CONTACT, DEVICES));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account.id".intern(), "account.gui".intern(), "account.email_address".intern(), "account.first_name".intern(), "account.middle_name".intern(), "account.last_name".intern(), "account.birth_date".intern(), "account.status".intern(), "account.last_update_time".intern(), "account.create_time".intern()));
    }

    public static interface AccountContactPNL {
        /**
         * Name of "AccountContact" entity. 
         */
        public static final String __ = "AccountContact".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property. 
         * type: long. 
         * column: "account_id". 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "mobile" property. 
         * type: String. 
         * column: "mobile". 
         */
        public static final String MOBILE = (__ + ".mobile").intern();

        /**
         * Name of "telephone" property. 
         * type: String. 
         * column: "telephone". 
         */
        public static final String TELEPHONE = (__ + ".telephone").intern();

        /**
         * Name of "email" property. 
         * type: String. 
         * column: "email". 
         */
        public static final String EMAIL = (__ + ".email").intern();

        /**
         * Name of "address" property. 
         * type: String. 
         * column: "address". 
         */
        public static final String ADDRESS = (__ + ".address").intern();

        /**
         * Name of "address2" property. 
         * type: String. 
         * column: "address_2". 
         */
        public static final String ADDRESS_2 = (__ + ".address2").intern();

        /**
         * Name of "city" property. 
         * type: String. 
         * column: "city". 
         */
        public static final String CITY = (__ + ".city").intern();

        /**
         * Name of "state" property. 
         * type: String. 
         * column: "state". 
         */
        public static final String STATE = (__ + ".state").intern();

        /**
         * Name of "country" property. 
         * type: String. 
         * column: "country". 
         */
        public static final String COUNTRY = (__ + ".country").intern();

        /**
         * Name of "zipCode" property. 
         * type: String. 
         * column: "zip_code". 
         */
        public static final String ZIP_CODE = (__ + ".zipCode").intern();

        /**
         * Name of "category" property. 
         * type: String. 
         * column: "category". 
         */
        public static final String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, MOBILE, TELEPHONE, EMAIL, ADDRESS, ADDRESS_2, CITY, STATE, COUNTRY, ZIP_CODE, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account_contact.id".intern(), "account_contact.account_id".intern(), "account_contact.mobile".intern(), "account_contact.telephone".intern(), "account_contact.email".intern(), "account_contact.address".intern(), "account_contact.address_2".intern(), "account_contact.city".intern(), "account_contact.state".intern(), "account_contact.country".intern(), "account_contact.zip_code".intern(), "account_contact.category".intern(), "account_contact.description".intern(), "account_contact.status".intern(), "account_contact.last_update_time".intern(), "account_contact.create_time".intern()));
    }

    public static interface AccountDevicePNL {
        /**
         * Name of "AccountDevice" entity. 
         */
        public static final String __ = "AccountDevice".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property. 
         * type: long. 
         * column: "account_id". 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "name" property. 
         * type: String. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "UDID" property. 
         * type: String. 
         * column: "udid". 
         */
        public static final String UDID = (__ + ".UDID").intern();

        /**
         * Name of "platform" property. 
         * type: String. 
         * column: "platform". 
         */
        public static final String PLATFORM = (__ + ".platform").intern();

        /**
         * Name of "model" property. 
         * type: String. 
         * column: "model". 
         */
        public static final String MODEL = (__ + ".model").intern();

        /**
         * Name of "manufacturer" property. 
         * type: String. 
         * column: "manufacturer". 
         */
        public static final String MANUFACTURER = (__ + ".manufacturer").intern();

        /**
         * Name of "produceTime" property. 
         * type: Timestamp. 
         * column: "produce_time". 
         */
        public static final String PRODUCE_TIME = (__ + ".produceTime").intern();

        /**
         * Name of "category" property. 
         * type: String. 
         * column: "category". 
         */
        public static final String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER, PRODUCE_TIME, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account_device.id".intern(), "account_device.account_id".intern(), "account_device.name".intern(), "account_device.udid".intern(), "account_device.platform".intern(), "account_device.model".intern(), "account_device.manufacturer".intern(), "account_device.produce_time".intern(), "account_device.category".intern(), "account_device.description".intern(), "account_device.status".intern(), "account_device.last_update_time".intern(), "account_device.create_time".intern()));
    }

    public static interface AclGroupPNL {
        /**
         * Name of "AclGroup" entity. 
         */
        public static final String __ = "AclGroup".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property. 
         * type: String. 
         * column: "gui". 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property. 
         * type: String. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "userList" property. 
         * type: List<com.landawn.abacus.entity.extendDirty.lv.AclUser>. 
         * column: "AclUser". 
         */
        public static final String USER_LIST = (__ + ".userList").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME, USER_LIST));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_group.id".intern(), "acl_group.gui".intern(), "acl_group.name".intern(), "acl_group.description".intern(), "acl_group.status".intern(), "acl_group.last_update_time".intern(), "acl_group.create_time".intern()));
    }

    public static interface AclTargetPNL {
        /**
         * Name of "AclTarget" entity. 
         */
        public static final String __ = "AclTarget".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property. 
         * type: String. 
         * column: "gui". 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property. 
         * type: String. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "category" property. 
         * type: String. 
         * column: "category". 
         */
        public static final String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "subCategory" property. 
         * type: String. 
         * column: "sub_category". 
         */
        public static final String SUB_CATEGORY = (__ + ".subCategory").intern();

        /**
         * Name of "type" property. 
         * type: String. 
         * column: "type". 
         */
        public static final String TYPE = (__ + ".type").intern();

        /**
         * Name of "subType" property. 
         * type: String. 
         * column: "sub_type". 
         */
        public static final String SUB_TYPE = (__ + ".subType").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, CATEGORY, SUB_CATEGORY, TYPE, SUB_TYPE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_target.id".intern(), "acl_target.gui".intern(), "acl_target.name".intern(), "acl_target.category".intern(), "acl_target.sub_category".intern(), "acl_target.type".intern(), "acl_target.sub_type".intern(), "acl_target.description".intern(), "acl_target.status".intern(), "acl_target.last_update_time".intern(), "acl_target.create_time".intern()));
    }

    public static interface AclUgTargetRelationshipPNL {
        /**
         * Name of "AclUgTargetRelationship" entity. 
         */
        public static final String __ = "AclUgTargetRelationship".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "ugGui" property. 
         * type: String. 
         * column: "ug_gui". 
         */
        public static final String UG_GUI = (__ + ".ugGui").intern();

        /**
         * Name of "targetGui" property. 
         * type: String. 
         * column: "target_gui". 
         */
        public static final String TARGET_GUI = (__ + ".targetGui").intern();

        /**
         * Name of "privilege" property. 
         * type: long. 
         * column: "privilege". 
         */
        public static final String PRIVILEGE = (__ + ".privilege").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, UG_GUI, TARGET_GUI, PRIVILEGE, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_ug_target_relationship.id".intern(), "acl_ug_target_relationship.ug_gui".intern(), "acl_ug_target_relationship.target_gui".intern(), "acl_ug_target_relationship.privilege".intern(), "acl_ug_target_relationship.description".intern(), "acl_ug_target_relationship.status".intern(), "acl_ug_target_relationship.last_update_time".intern(), "acl_ug_target_relationship.create_time".intern()));
    }

    public static interface AclUserPNL {
        /**
         * Name of "AclUser" entity. 
         */
        public static final String __ = "AclUser".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property. 
         * type: String. 
         * column: "gui". 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "name" property. 
         * type: String. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "groupList" property. 
         * type: List<com.landawn.abacus.entity.extendDirty.lv.AclGroup>. 
         * column: "AclGroup". 
         */
        public static final String GROUP_LIST = (__ + ".groupList").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, NAME, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME, GROUP_LIST));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_user.id".intern(), "acl_user.gui".intern(), "acl_user.name".intern(), "acl_user.description".intern(), "acl_user.status".intern(), "acl_user.last_update_time".intern(), "acl_user.create_time".intern()));
    }

    public static interface AclUserGroupRelationshipPNL {
        /**
         * Name of "AclUserGroupRelationship" entity. 
         */
        public static final String __ = "AclUserGroupRelationship".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "userGUI" property. 
         * type: String. 
         * column: "user_gui". 
         */
        public static final String USER_GUI = (__ + ".userGUI").intern();

        /**
         * Name of "groupGUI" property. 
         * type: String. 
         * column: "group_gui". 
         */
        public static final String GROUP_GUI = (__ + ".groupGUI").intern();

        /**
         * Name of "description" property. 
         * type: String. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, USER_GUI, GROUP_GUI, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("acl_user_group_relationship.id".intern(), "acl_user_group_relationship.user_gui".intern(), "acl_user_group_relationship.group_gui".intern(), "acl_user_group_relationship.description".intern(), "acl_user_group_relationship.status".intern(), "acl_user_group_relationship.last_update_time".intern(), "acl_user_group_relationship.create_time".intern()));
    }

    public static interface DataTypePNL {
        /**
         * Name of "DataType" entity. 
         */
        public static final String __ = "DataType".intern();

        /**
         * Name of "byteType" property. 
         * type: byte. 
         * column: "bytetype". 
         */
        public static final String BYTE_TYPE = (__ + ".byteType").intern();

        /**
         * Name of "charType" property. 
         * type: char. 
         * column: "chartype". 
         */
        public static final String CHAR_TYPE = (__ + ".charType").intern();

        /**
         * Name of "booleanType" property. 
         * type: boolean. 
         * column: "booleantype". 
         */
        public static final String BOOLEAN_TYPE = (__ + ".booleanType").intern();

        /**
         * Name of "shortType" property. 
         * type: short. 
         * column: "shorttype". 
         */
        public static final String SHORT_TYPE = (__ + ".shortType").intern();

        /**
         * Name of "intType" property. 
         * type: int. 
         * column: "inttype". 
         */
        public static final String INT_TYPE = (__ + ".intType").intern();

        /**
         * Name of "longType" property. 
         * type: long. 
         * column: "longtype". 
         */
        public static final String LONG_TYPE = (__ + ".longType").intern();

        /**
         * Name of "floatType" property. 
         * type: float. 
         * column: "floattype". 
         */
        public static final String FLOAT_TYPE = (__ + ".floatType").intern();

        /**
         * Name of "doubleType" property. 
         * type: double. 
         * column: "doubletype". 
         */
        public static final String DOUBLE_TYPE = (__ + ".doubleType").intern();

        /**
         * Name of "bigIntegerType" property. 
         * type: BigInteger. 
         * column: "bigIntegerType". 
         */
        public static final String BIG_INTEGER_TYPE = (__ + ".bigIntegerType").intern();

        /**
         * Name of "bigDecimalType" property. 
         * type: BigDecimal. 
         * column: "bigdecimaltype". 
         */
        public static final String BIG_DECIMAL_TYPE = (__ + ".bigDecimalType").intern();

        /**
         * Name of "stringType" property. 
         * type: String. 
         * column: "stringtype". 
         */
        public static final String STRING_TYPE = (__ + ".stringType").intern();

        /**
         * Name of "byteArrayType" property. 
         * type: byte[]. 
         * column: "bytearraytype". 
         */
        public static final String BYTE_ARRAY_TYPE = (__ + ".byteArrayType").intern();

        /**
         * Name of "characterStreamType" property. 
         * type: CharacterStream. 
         * column: "characterstreamtype". 
         */
        public static final String CHARACTER_STREAM_TYPE = (__ + ".characterStreamType").intern();

        /**
         * Name of "binaryStreamType" property. 
         * type: BinaryStream. 
         * column: "binarystreamtype". 
         */
        public static final String BINARY_STREAM_TYPE = (__ + ".binaryStreamType").intern();

        /**
         * Name of "clobType" property. 
         * type: Clob. 
         * column: "clobtype". 
         */
        public static final String CLOB_TYPE = (__ + ".clobType").intern();

        /**
         * Name of "blobType" property. 
         * type: Blob. 
         * column: "blobtype". 
         */
        public static final String BLOB_TYPE = (__ + ".blobType").intern();

        /**
         * Name of "dateType" property. 
         * type: Date. 
         * column: "datetype". 
         */
        public static final String DATE_TYPE = (__ + ".dateType").intern();

        /**
         * Name of "timeType" property. 
         * type: Time. 
         * column: "timetype". 
         */
        public static final String TIME_TYPE = (__ + ".timeType").intern();

        /**
         * Name of "timestampType" property. 
         * type: Timestamp. 
         * column: "timestamptype". 
         */
        public static final String TIMESTAMP_TYPE = (__ + ".timestampType").intern();

        /**
         * Name of "longDateType" property. 
         * type: long. 
         * column: "longDateType". 
         */
        public static final String LONG_DATE_TYPE = (__ + ".longDateType").intern();

        /**
         * Name of "longTimeType" property. 
         * type: long. 
         * column: "longTimeType". 
         */
        public static final String LONG_TIME_TYPE = (__ + ".longTimeType").intern();

        /**
         * Name of "longTimestampType" property. 
         * type: long. 
         * column: "longTimestampType". 
         */
        public static final String LONG_TIMESTAMP_TYPE = (__ + ".longTimestampType").intern();

        /**
         * Name of "enumType" property. 
         * type: com.landawn.abacus.types.WeekDay. 
         * column: "enumType". 
         */
        public static final String ENUM_TYPE = (__ + ".enumType").intern();

        /**
         * Name of "stringArrayListType" property. 
         * type: ArrayList<String>. 
         * column: "stringarraylisttype". 
         */
        public static final String STRING_ARRAY_LIST_TYPE = (__ + ".stringArrayListType").intern();

        /**
         * Name of "booleanLinkedListType" property. 
         * type: LinkedList<Boolean>. 
         * column: "booleanlinkedlisttype". 
         */
        public static final String BOOLEAN_LINKED_LIST_TYPE = (__ + ".booleanLinkedListType").intern();

        /**
         * Name of "doubleListType" property. 
         * type: List<Double>. 
         * column: "doublearraylisttype". 
         */
        public static final String DOUBLE_LIST_TYPE = (__ + ".doubleListType").intern();

        /**
         * Name of "dateArrayListType" property. 
         * type: ArrayList<Date>. 
         * column: "datearraylisttype". 
         */
        public static final String DATE_ARRAY_LIST_TYPE = (__ + ".dateArrayListType").intern();

        /**
         * Name of "timestampArrayListType" property. 
         * type: ArrayList<Timestamp>. 
         * column: "timestamparraylisttype". 
         */
        public static final String TIMESTAMP_ARRAY_LIST_TYPE = (__ + ".timestampArrayListType").intern();

        /**
         * Name of "bigDecimalArrayListType" property. 
         * type: ArrayList<BigDecimal>. 
         * column: "bigdecimalarraylisttype". 
         */
        public static final String BIG_DECIMAL_ARRAY_LIST_TYPE = (__ + ".bigDecimalArrayListType").intern();

        /**
         * Name of "stringHashSetType" property. 
         * type: HashSet<String>. 
         * column: "stringhashsettype". 
         */
        public static final String STRING_HASH_SET_TYPE = (__ + ".stringHashSetType").intern();

        /**
         * Name of "booleanLinkedHashSetType" property. 
         * type: LinkedHashSet<Boolean>. 
         * column: "booleanlinkedhashsettype". 
         */
        public static final String BOOLEAN_LINKED_HASH_SET_TYPE = (__ + ".booleanLinkedHashSetType").intern();

        /**
         * Name of "dateHashSetType" property. 
         * type: HashSet<Date>. 
         * column: "datehashsettype". 
         */
        public static final String DATE_HASH_SET_TYPE = (__ + ".dateHashSetType").intern();

        /**
         * Name of "timestampHashSetType" property. 
         * type: HashSet<Timestamp>. 
         * column: "timestamphashsettype". 
         */
        public static final String TIMESTAMP_HASH_SET_TYPE = (__ + ".timestampHashSetType").intern();

        /**
         * Name of "bigDecimalHashSetType" property. 
         * type: HashSet<BigDecimal>. 
         * column: "bigdecimalhashsettype". 
         */
        public static final String BIG_DECIMAL_HASH_SET_TYPE = (__ + ".bigDecimalHashSetType").intern();

        /**
         * Name of "stringHashMapType" property. 
         * type: HashMap<String, String>. 
         * column: "stringhashmaptype". 
         */
        public static final String STRING_HASH_MAP_TYPE = (__ + ".stringHashMapType").intern();

        /**
         * Name of "booleanLinkedHashMapType" property. 
         * type: LinkedHashMap<String, Boolean>. 
         * column: "booleanlinkedhashmaptype". 
         */
        public static final String BOOLEAN_LINKED_HASH_MAP_TYPE = (__ + ".booleanLinkedHashMapType").intern();

        /**
         * Name of "floatHashMapType" property. 
         * type: HashMap<String, Float>. 
         * column: "floathashmaptype". 
         */
        public static final String FLOAT_HASH_MAP_TYPE = (__ + ".floatHashMapType").intern();

        /**
         * Name of "dateHashMapType" property. 
         * type: HashMap<String, Date>. 
         * column: "datehashmaptype". 
         */
        public static final String DATE_HASH_MAP_TYPE = (__ + ".dateHashMapType").intern();

        /**
         * Name of "timestampHashMapType" property. 
         * type: HashMap<Timestamp, Float>. 
         * column: "timestamphashmaptype". 
         */
        public static final String TIMESTAMP_HASH_MAP_TYPE = (__ + ".timestampHashMapType").intern();

        /**
         * Name of "bigDecimalHashMapType" property. 
         * type: HashMap<BigDecimal, String>. 
         * column: "bigdecimalhashmaptype". 
         */
        public static final String BIG_DECIMAL_HASH_MAP_TYPE = (__ + ".bigDecimalHashMapType").intern();

        /**
         * Name of "stringVectorType" property. 
         * type: Vector<String>. 
         * column: "stringvectortype". 
         */
        public static final String STRING_VECTOR_TYPE = (__ + ".stringVectorType").intern();

        /**
         * Name of "stringConcurrentHashMapType" property. 
         * type: ConcurrentHashMap<BigDecimal, String>. 
         * column: "stringconcurrenthashmaptype". 
         */
        public static final String STRING_CONCURRENT_HASH_MAP_TYPE = (__ + ".stringConcurrentHashMapType").intern();

        /**
         * Name of "jsonType" property. 
         * type: JSON<com.landawn.abacus.entity.extendDirty.lvc.Account>. 
         * column: "jsonType". 
         */
        public static final String JSON_TYPE = (__ + ".jsonType").intern();

        /**
         * Name of "xmlType" property. 
         * type: XML<com.landawn.abacus.entity.extendDirty.lvc.Account>. 
         * column: "xmlType". 
         */
        public static final String XML_TYPE = (__ + ".xmlType").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(BYTE_TYPE, CHAR_TYPE, BOOLEAN_TYPE, SHORT_TYPE, INT_TYPE, LONG_TYPE, FLOAT_TYPE, DOUBLE_TYPE, BIG_INTEGER_TYPE, BIG_DECIMAL_TYPE, STRING_TYPE, BYTE_ARRAY_TYPE, CHARACTER_STREAM_TYPE, BINARY_STREAM_TYPE, CLOB_TYPE, BLOB_TYPE, DATE_TYPE, TIME_TYPE, TIMESTAMP_TYPE, LONG_DATE_TYPE, LONG_TIME_TYPE, LONG_TIMESTAMP_TYPE, ENUM_TYPE, STRING_ARRAY_LIST_TYPE, BOOLEAN_LINKED_LIST_TYPE, DOUBLE_LIST_TYPE, DATE_ARRAY_LIST_TYPE, TIMESTAMP_ARRAY_LIST_TYPE, BIG_DECIMAL_ARRAY_LIST_TYPE, STRING_HASH_SET_TYPE, BOOLEAN_LINKED_HASH_SET_TYPE, DATE_HASH_SET_TYPE, TIMESTAMP_HASH_SET_TYPE, BIG_DECIMAL_HASH_SET_TYPE, STRING_HASH_MAP_TYPE, BOOLEAN_LINKED_HASH_MAP_TYPE, FLOAT_HASH_MAP_TYPE, DATE_HASH_MAP_TYPE, TIMESTAMP_HASH_MAP_TYPE, BIG_DECIMAL_HASH_MAP_TYPE, STRING_VECTOR_TYPE, STRING_CONCURRENT_HASH_MAP_TYPE, JSON_TYPE, XML_TYPE));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("data_type.bytetype".intern(), "data_type.chartype".intern(), "data_type.booleantype".intern(), "data_type.shorttype".intern(), "data_type.inttype".intern(), "data_type.longtype".intern(), "data_type.floattype".intern(), "data_type.doubletype".intern(), "data_type.bigIntegerType".intern(), "data_type.bigdecimaltype".intern(), "data_type.stringtype".intern(), "data_type.bytearraytype".intern(), "data_type.characterstreamtype".intern(), "data_type.binarystreamtype".intern(), "data_type.clobtype".intern(), "data_type.blobtype".intern(), "data_type.datetype".intern(), "data_type.timetype".intern(), "data_type.timestamptype".intern(), "data_type.longDateType".intern(), "data_type.longTimeType".intern(), "data_type.longTimestampType".intern(), "data_type.enumType".intern(), "data_type.stringarraylisttype".intern(), "data_type.booleanlinkedlisttype".intern(), "data_type.doublearraylisttype".intern(), "data_type.datearraylisttype".intern(), "data_type.timestamparraylisttype".intern(), "data_type.bigdecimalarraylisttype".intern(), "data_type.stringhashsettype".intern(), "data_type.booleanlinkedhashsettype".intern(), "data_type.datehashsettype".intern(), "data_type.timestamphashsettype".intern(), "data_type.bigdecimalhashsettype".intern(), "data_type.stringhashmaptype".intern(), "data_type.booleanlinkedhashmaptype".intern(), "data_type.floathashmaptype".intern(), "data_type.datehashmaptype".intern(), "data_type.timestamphashmaptype".intern(), "data_type.bigdecimalhashmaptype".intern(), "data_type.stringvectortype".intern(), "data_type.stringconcurrenthashmaptype".intern(), "data_type.jsonType".intern(), "data_type.xmlType".intern()));
    }

    public static interface LoginPNL {
        /**
         * Name of "Login" entity. 
         */
        public static final String __ = "Login".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property. 
         * type: long. 
         * column: "account_id". 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "loginId" property. 
         * type: String. 
         * column: "login_id". 
         */
        public static final String LOGIN_ID = (__ + ".loginId").intern();

        /**
         * Name of "loginPassword" property. 
         * type: String. 
         * column: "login_password". 
         */
        public static final String LOGIN_PASSWORD = (__ + ".loginPassword").intern();

        /**
         * Name of "status" property. 
         * type: int. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: Timestamp. 
         * column: "last_update_time". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Timestamp. 
         * column: "create_time". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, LOGIN_ID, LOGIN_PASSWORD, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("login.id".intern(), "login.account_id".intern(), "login.login_id".intern(), "login.login_password".intern(), "login.status".intern(), "login.last_update_time".intern(), "login.create_time".intern()));
    }

    public static final String ACCOUNT_ID = "accountId".intern();

    public static final String ADDRESS = "address".intern();

    public static final String ADDRESS_2 = "address2".intern();

    public static final String BIG_DECIMAL_ARRAY_LIST_TYPE = "bigDecimalArrayListType".intern();

    public static final String BIG_DECIMAL_HASH_MAP_TYPE = "bigDecimalHashMapType".intern();

    public static final String BIG_DECIMAL_HASH_SET_TYPE = "bigDecimalHashSetType".intern();

    public static final String BIG_DECIMAL_TYPE = "bigDecimalType".intern();

    public static final String BIG_INTEGER_TYPE = "bigIntegerType".intern();

    public static final String BINARY_STREAM_TYPE = "binaryStreamType".intern();

    public static final String BIRTH_DATE = "birthDate".intern();

    public static final String BLOB_TYPE = "blobType".intern();

    public static final String BOOLEAN_LINKED_HASH_MAP_TYPE = "booleanLinkedHashMapType".intern();

    public static final String BOOLEAN_LINKED_HASH_SET_TYPE = "booleanLinkedHashSetType".intern();

    public static final String BOOLEAN_LINKED_LIST_TYPE = "booleanLinkedListType".intern();

    public static final String BOOLEAN_TYPE = "booleanType".intern();

    public static final String BYTE_ARRAY_TYPE = "byteArrayType".intern();

    public static final String BYTE_TYPE = "byteType".intern();

    public static final String CATEGORY = "category".intern();

    public static final String CHARACTER_STREAM_TYPE = "characterStreamType".intern();

    public static final String CHAR_TYPE = "charType".intern();

    public static final String CITY = "city".intern();

    public static final String CLOB_TYPE = "clobType".intern();

    public static final String CONTACT = "contact".intern();

    public static final String COUNTRY = "country".intern();

    public static final String CREATE_TIME = "createTime".intern();

    public static final String DATE_ARRAY_LIST_TYPE = "dateArrayListType".intern();

    public static final String DATE_HASH_MAP_TYPE = "dateHashMapType".intern();

    public static final String DATE_HASH_SET_TYPE = "dateHashSetType".intern();

    public static final String DATE_TYPE = "dateType".intern();

    public static final String DESCRIPTION = "description".intern();

    public static final String DEVICES = "devices".intern();

    public static final String DOUBLE_LIST_TYPE = "doubleListType".intern();

    public static final String DOUBLE_TYPE = "doubleType".intern();

    public static final String EMAIL = "email".intern();

    public static final String EMAIL_ADDRESS = "emailAddress".intern();

    public static final String ENUM_TYPE = "enumType".intern();

    public static final String FIRST_NAME = "firstName".intern();

    public static final String FLOAT_HASH_MAP_TYPE = "floatHashMapType".intern();

    public static final String FLOAT_TYPE = "floatType".intern();

    public static final String GROUP_GUI = "groupGUI".intern();

    public static final String GROUP_LIST = "groupList".intern();

    public static final String GUI = "gui".intern();

    public static final String ID = "id".intern();

    public static final String INT_TYPE = "intType".intern();

    public static final String JSON_TYPE = "jsonType".intern();

    public static final String LAST_NAME = "lastName".intern();

    public static final String LAST_UPDATE_TIME = "lastUpdateTime".intern();

    public static final String LOGIN_ID = "loginId".intern();

    public static final String LOGIN_PASSWORD = "loginPassword".intern();

    public static final String LONG_DATE_TYPE = "longDateType".intern();

    public static final String LONG_TIMESTAMP_TYPE = "longTimestampType".intern();

    public static final String LONG_TIME_TYPE = "longTimeType".intern();

    public static final String LONG_TYPE = "longType".intern();

    public static final String MANUFACTURER = "manufacturer".intern();

    public static final String MIDDLE_NAME = "middleName".intern();

    public static final String MOBILE = "mobile".intern();

    public static final String MODEL = "model".intern();

    public static final String NAME = "name".intern();

    public static final String PLATFORM = "platform".intern();

    public static final String PRIVILEGE = "privilege".intern();

    public static final String PRODUCE_TIME = "produceTime".intern();

    public static final String SHORT_TYPE = "shortType".intern();

    public static final String STATE = "state".intern();

    public static final String STATUS = "status".intern();

    public static final String STRING_ARRAY_LIST_TYPE = "stringArrayListType".intern();

    public static final String STRING_CONCURRENT_HASH_MAP_TYPE = "stringConcurrentHashMapType".intern();

    public static final String STRING_HASH_MAP_TYPE = "stringHashMapType".intern();

    public static final String STRING_HASH_SET_TYPE = "stringHashSetType".intern();

    public static final String STRING_TYPE = "stringType".intern();

    public static final String STRING_VECTOR_TYPE = "stringVectorType".intern();

    public static final String SUB_CATEGORY = "subCategory".intern();

    public static final String SUB_TYPE = "subType".intern();

    public static final String TARGET_GUI = "targetGui".intern();

    public static final String TELEPHONE = "telephone".intern();

    public static final String TIMESTAMP_ARRAY_LIST_TYPE = "timestampArrayListType".intern();

    public static final String TIMESTAMP_HASH_MAP_TYPE = "timestampHashMapType".intern();

    public static final String TIMESTAMP_HASH_SET_TYPE = "timestampHashSetType".intern();

    public static final String TIMESTAMP_TYPE = "timestampType".intern();

    public static final String TIME_TYPE = "timeType".intern();

    public static final String TYPE = "type".intern();

    public static final String UDID = "UDID".intern();

    public static final String UG_GUI = "ugGui".intern();

    public static final String USER_GUI = "userGUI".intern();

    public static final String USER_LIST = "userList".intern();

    public static final String XML_TYPE = "xmlType".intern();

    public static final String ZIP_CODE = "zipCode".intern();
}
