/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity;

import java.sql.Timestamp;
import java.util.Objects;
import com.landawn.abacus.annotation.Id;
import com.landawn.abacus.annotation.Column;
import com.landawn.abacus.core.AbstractDirtyMarker;
import com.landawn.abacus.entity.CodesPNL;


/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Account extends AbstractDirtyMarker implements CodesPNL.AccountPNL {

    @Id
    @Column("id")
    private long id;

    @Column("first_name")
    private String firstName;

    @Column("last_name")
    private String lastName;

    @Column("email_address")
    private String emailAddress;

    @Column("create_time")
    private Timestamp createTime;

    public Account() {
        super(__);
    }

    public Account(long id) {
        this();

        setId(id);
    }

    public Account(String firstName, String lastName, String emailAddress, 
        Timestamp createTime) {
        this();

        setFirstName(firstName);
        setLastName(lastName);
        setEmailAddress(emailAddress);
        setCreateTime(createTime);
    }

    public Account(long id, String firstName, String lastName, String emailAddress, 
        Timestamp createTime) {
        this();

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setEmailAddress(emailAddress);
        setCreateTime(createTime);
    }

    public long getId() {
        return id;
    }

    public Account setId(long id) {
        super.setUpdatedPropName(ID);
        this.id = id;

        return this;
    }

    public String getFirstName() {
        return firstName;
    }

    public Account setFirstName(String firstName) {
        super.setUpdatedPropName(FIRST_NAME);
        this.firstName = firstName;

        return this;
    }

    public String getLastName() {
        return lastName;
    }

    public Account setLastName(String lastName) {
        super.setUpdatedPropName(LAST_NAME);
        this.lastName = lastName;

        return this;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public Account setEmailAddress(String emailAddress) {
        super.setUpdatedPropName(EMAIL_ADDRESS);
        this.emailAddress = emailAddress;

        return this;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public Account setCreateTime(Timestamp createTime) {
        super.setUpdatedPropName(CREATE_TIME);
        this.createTime = createTime;

        return this;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(id);
        h = 31 * h + Objects.hashCode(firstName);
        h = 31 * h + Objects.hashCode(lastName);
        h = 31 * h + Objects.hashCode(emailAddress);
        h = 31 * h + Objects.hashCode(createTime);

        return h;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Account) {
            final Account other = (Account) obj;

            return Objects.equals(id, other.id)
                && Objects.equals(firstName, other.firstName)
                && Objects.equals(lastName, other.lastName)
                && Objects.equals(emailAddress, other.emailAddress)
                && Objects.equals(createTime, other.createTime);
        }

        return false;
    }

    @Override
    public String toString() {
         return "{id=" + Objects.toString(id)
                 + ", firstName=" + Objects.toString(firstName)
                 + ", lastName=" + Objects.toString(lastName)
                 + ", emailAddress=" + Objects.toString(emailAddress)
                 + ", createTime=" + Objects.toString(createTime)
                 + "}";
    }
}
