package com.myPackage.x;

import java.sql.Date;
import java.util.LinkedHashMap;
import java.util.Objects;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Account {

    private String firstName;
    private String lastName;
    private Date birthdate;
    private LinkedHashMap<String, Integer> attrs;

    public String getFirstName() {
        return firstName;
    }

    public Account setFirstName(String firstName) {
        this.firstName = firstName;

        return this;
    }

    public String getLastName() {
        return lastName;
    }

    public Account setLastName(String lastName) {
        this.lastName = lastName;

        return this;
    }

    public Date getBirthdate() {
        return birthdate;
    }

    public Account setBirthdate(Date birthdate) {
        this.birthdate = birthdate;

        return this;
    }

    public LinkedHashMap<String, Integer> getAttrs() {
        return attrs;
    }

    public Account setAttrs(LinkedHashMap<String, Integer> attrs) {
        this.attrs = attrs;

        return this;
    }

    @Override
    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(firstName);
        h = 31 * h + Objects.hashCode(lastName);
        h = 31 * h + Objects.hashCode(birthdate);
        h = 31 * h + Objects.hashCode(attrs);

        return h;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Account) {
            final Account other = (Account) obj;

            return Objects.equals(firstName, other.firstName)
                && Objects.equals(lastName, other.lastName)
                && Objects.equals(birthdate, other.birthdate)
                && Objects.equals(attrs, other.attrs);
        }

        return false;
    }

    @Override
    public String toString() {
        return "{firstName=" + Objects.toString(firstName)
                 + ", lastName=" + Objects.toString(lastName)
                 + ", birthdate=" + Objects.toString(birthdate)
                 + ", attrs=" + Objects.toString(attrs)
                 + "}";
    }
}
