/*
 * Copyright (C) 2015 HaiYang Li
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.landawn.abacus.metadata;

import java.util.List;
import java.util.Map;

import com.landawn.abacus.idGenerator.IdGenerator;

/**
 * 
 * @since 0.8
 * 
 * @author Haiyang Li
 */
public interface EntityDefinition {
    String getName();

    String getTableName();

    String getJavaType();

    <T> Class<T> getTypeClass();

    <T> Class<T> getArrayTypeClass();

    List<Property> getPropertyList();

    List<String> getPropertyNameList();

    Property getProperty(String propName);

    List<IdGenerator<Object>> getIdGeneratorList();

    IdGenerator<Object> getIdGenerator(String propName);

    List<Property> getIdPropertyList();

    List<String> getIdPropertyNameList();

    List<Property> getUIDPropertyList();

    List<String> getUIDPropertyNameList();

    List<Property> getEntiyPropertyList();

    List<Property> getDefaultLoadPropertyList();

    List<String> getDefaultLoadPropertyNameList();

    List<Property> getDefaultOnInsertPropertyList();

    List<Property> getDefaultOnUpdatePropertyList();

    boolean isIdAutoGenerated();

    boolean isSliceEntity();

    List<EntityDefinition> getSliceEntityList();

    Map<String, String> getAttributes();

    String getAttribute(String attrName);

    EntityDefinition getParentEntity();

    EntityDefinitionFactory getFactory();
}
