/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.hbase;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public interface HbaseCNL {
    public static final String _DN = "hbase".intern();

    public static interface AccountCNL {
        /**
         * Name of "account" table. 
         */
        public static final String __ = "account".intern();

        /**
         * Name of "id" column. 
         * Java type: long. 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" column. 
         * Java type: Map<Long, HBaseColumn<String>>. 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "emailAddress" column. 
         * Java type: SortedMap<Long, HBaseColumn<String>>. 
         */
        public static final String EMAIL_ADDRESS = (__ + ".emailAddress").intern();

        /**
         * Name of "name" column. 
         * Java type: com.landawn.abacus.entity.hbase.Name. 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "status" column. 
         * Java type: HBaseColumn<Integer>. 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" column. 
         * Java type: LinkedHashMap<Long, HBaseColumn<Timestamp>>. 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" column. 
         * Java type: Map<Long, HBaseColumn<Timestamp>>. 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "contact" column. 
         * Java type: com.landawn.abacus.entity.hbase.AccountContact. 
         */
        public static final String CONTACT = (__ + ".contact").intern();

        /**
         * Name of "strSet" column. 
         * Java type: Set<String>. 
         */
        public static final String STR_SET = (__ + ".strSet").intern();

        /**
         * Name of "strMap" column. 
         * Java type: Map<String, Long>. 
         */
        public static final String STR_MAP = (__ + ".strMap").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, GUI, EMAIL_ADDRESS, NAME, STATUS, LAST_UPDATE_TIME, CREATE_TIME, CONTACT, STR_SET, STR_MAP));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList("Account.id".intern(), "Account.gui".intern(), "Account.emailAddress".intern(), "Account.name".intern(), "Account.status".intern(), "Account.lastUpdateTime".intern(), "Account.createTime".intern(), "Account.contact".intern(), "Account.strSet".intern(), "Account.strMap".intern()));
    }

    public static interface NameCNL {
        /**
         * Name of "Name" table. 
         */
        public static final String __ = "Name".intern();

        /**
         * Name of "firstName" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String FIRST_NAME = (__ + ".firstName").intern();

        /**
         * Name of "middleName" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String MIDDLE_NAME = (__ + ".middleName").intern();

        /**
         * Name of "lastName" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String LAST_NAME = (__ + ".lastName").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList(FIRST_NAME, MIDDLE_NAME, LAST_NAME));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList("Name.firstName".intern(), "Name.middleName".intern(), "Name.lastName".intern()));
    }

    public static interface AccountContactCNL {
        /**
         * Name of "account_contact" table. 
         */
        public static final String __ = "account_contact".intern();

        /**
         * Name of "id" column. 
         * Java type: HBaseColumn<Long>. 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" column. 
         * Java type: List<HBaseColumn<Long>>. 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "telephone" column. 
         * Java type: SortedSet<HBaseColumn<String>>. 
         */
        public static final String TELEPHONE = (__ + ".telephone").intern();

        /**
         * Name of "city" column. 
         * Java type: Set<HBaseColumn<String>>. 
         */
        public static final String CITY = (__ + ".city").intern();

        /**
         * Name of "state" column. 
         * Java type: LinkedHashSet<HBaseColumn<String>>. 
         */
        public static final String STATE = (__ + ".state").intern();

        /**
         * Name of "zipCode" column. 
         * Java type: List<HBaseColumn<String>>. 
         */
        public static final String ZIP_CODE = (__ + ".zipCode").intern();

        /**
         * Name of "status" column. 
         * Java type: List<HBaseColumn<Integer>>. 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" column. 
         * Java type: List<HBaseColumn<Timestamp>>. 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" column. 
         * Java type: List<HBaseColumn<Timestamp>>. 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, TELEPHONE, CITY, STATE, ZIP_CODE, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AccountContact.id".intern(), "AccountContact.accountId".intern(), "AccountContact.telephone".intern(), "AccountContact.city".intern(), "AccountContact.state".intern(), "AccountContact.zipCode".intern(), "AccountContact.status".intern(), "AccountContact.lastUpdateTime".intern(), "AccountContact.createTime".intern()));
    }

    public static interface AccountDeviceCNL {
        /**
         * Name of "account_device" table. 
         */
        public static final String __ = "account_device".intern();

        /**
         * Name of "id" column. 
         * Java type: HBaseColumn<Long>. 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" column. 
         * Java type: HBaseColumn<Long>. 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "name" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "UDID" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String UDID = (__ + ".UDID").intern();

        /**
         * Name of "platform" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String PLATFORM = (__ + ".platform").intern();

        /**
         * Name of "model" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String MODEL = (__ + ".model").intern();

        /**
         * Name of "manufacturer" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String MANUFACTURER = (__ + ".manufacturer").intern();

        /**
         * Name of "produceTime" column. 
         * Java type: HBaseColumn<Timestamp>. 
         */
        public static final String PRODUCE_TIME = (__ + ".produceTime").intern();

        /**
         * Name of "category" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" column. 
         * Java type: HBaseColumn<String>. 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" column. 
         * Java type: HBaseColumn<Integer>. 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" column. 
         * Java type: HBaseColumn<Timestamp>. 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" column. 
         * Java type: HBaseColumn<Timestamp>. 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER, PRODUCE_TIME, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList("AccountDevice.id".intern(), "AccountDevice.accountId".intern(), "AccountDevice.name".intern(), "AccountDevice.UDID".intern(), "AccountDevice.platform".intern(), "AccountDevice.model".intern(), "AccountDevice.manufacturer".intern(), "AccountDevice.produceTime".intern(), "AccountDevice.category".intern(), "AccountDevice.description".intern(), "AccountDevice.status".intern(), "AccountDevice.lastUpdateTime".intern(), "AccountDevice.createTime".intern()));
    }

    public static final String ACCOUNT_ID = "accountId".intern();

    public static final String CATEGORY = "category".intern();

    public static final String CITY = "city".intern();

    public static final String CONTACT = "contact".intern();

    public static final String CREATE_TIME = "createTime".intern();

    public static final String DESCRIPTION = "description".intern();

    public static final String EMAIL_ADDRESS = "emailAddress".intern();

    public static final String FIRST_NAME = "firstName".intern();

    public static final String GUI = "gui".intern();

    public static final String ID = "id".intern();

    public static final String LAST_NAME = "lastName".intern();

    public static final String LAST_UPDATE_TIME = "lastUpdateTime".intern();

    public static final String MANUFACTURER = "manufacturer".intern();

    public static final String MIDDLE_NAME = "middleName".intern();

    public static final String MODEL = "model".intern();

    public static final String NAME = "name".intern();

    public static final String PLATFORM = "platform".intern();

    public static final String PRODUCE_TIME = "produceTime".intern();

    public static final String STATE = "state".intern();

    public static final String STATUS = "status".intern();

    public static final String STR_MAP = "strMap".intern();

    public static final String STR_SET = "strSet".intern();

    public static final String TELEPHONE = "telephone".intern();

    public static final String UDID = "UDID".intern();

    public static final String ZIP_CODE = "zipCode".intern();
}
