/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.hbase;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public interface HbasePNL {
    public static final String _DN = "hbase".intern();

    public static interface AccountPNL {
        /**
         * Name of "Account" entity. 
         */
        public static final String __ = "Account".intern();

        /**
         * Name of "id" property. 
         * type: long. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "gui" property. 
         * type: Map<Long, HBaseColumn<String>>. 
         * column: "gui". 
         */
        public static final String GUI = (__ + ".gui").intern();

        /**
         * Name of "emailAddress" property. 
         * type: SortedMap<Long, HBaseColumn<String>>. 
         * column: "emailAddress". 
         */
        public static final String EMAIL_ADDRESS = (__ + ".emailAddress").intern();

        /**
         * Name of "name" property. 
         * type: com.landawn.abacus.entity.hbase.Name. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "status" property. 
         * type: HBaseColumn<Integer>. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: LinkedHashMap<Long, HBaseColumn<Timestamp>>. 
         * column: "lastUpdateTime". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: Map<Long, HBaseColumn<Timestamp>>. 
         * column: "createTime". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Name of "contact" property. 
         * type: com.landawn.abacus.entity.hbase.AccountContact. 
         * column: "contact". 
         */
        public static final String CONTACT = (__ + ".contact").intern();

        /**
         * Name of "strSet" property. 
         * type: Set<String>. 
         * column: "strSet". 
         */
        public static final String STR_SET = (__ + ".strSet").intern();

        /**
         * Name of "strMap" property. 
         * type: Map<String, Long>. 
         * column: "strMap". 
         */
        public static final String STR_MAP = (__ + ".strMap").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections
                .unmodifiableList(Arrays.asList(ID, GUI, EMAIL_ADDRESS, NAME, STATUS, LAST_UPDATE_TIME, CREATE_TIME, CONTACT, STR_SET, STR_MAP));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account.id".intern(), "account.gui".intern(),
                "account.emailAddress".intern(), "account.name".intern(), "account.status".intern(), "account.lastUpdateTime".intern(),
                "account.createTime".intern(), "account.contact".intern(), "account.strSet".intern(), "account.strMap".intern()));
    }

    public static interface NamePNL {
        /**
         * Name of "Name" entity. 
         */
        public static final String __ = "Name".intern();

        /**
         * Name of "firstName" property. 
         * type: HBaseColumn<String>. 
         * column: "firstName". 
         */
        public static final String FIRST_NAME = (__ + ".firstName").intern();

        /**
         * Name of "middleName" property. 
         * type: HBaseColumn<String>. 
         * column: "middleName". 
         */
        public static final String MIDDLE_NAME = (__ + ".middleName").intern();

        /**
         * Name of "lastName" property. 
         * type: HBaseColumn<String>. 
         * column: "lastName". 
         */
        public static final String LAST_NAME = (__ + ".lastName").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(FIRST_NAME, MIDDLE_NAME, LAST_NAME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections
                .unmodifiableList(Arrays.asList("Name.firstName".intern(), "Name.middleName".intern(), "Name.lastName".intern()));
    }

    public static interface AccountContactPNL {
        /**
         * Name of "AccountContact" entity. 
         */
        public static final String __ = "AccountContact".intern();

        /**
         * Name of "id" property. 
         * type: HBaseColumn<Long>. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property. 
         * type: List<HBaseColumn<Long>>. 
         * column: "accountId". 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "telephone" property. 
         * type: SortedSet<HBaseColumn<String>>. 
         * column: "telephone". 
         */
        public static final String TELEPHONE = (__ + ".telephone").intern();

        /**
         * Name of "city" property. 
         * type: Set<HBaseColumn<String>>. 
         * column: "city". 
         */
        public static final String CITY = (__ + ".city").intern();

        /**
         * Name of "state" property. 
         * type: LinkedHashSet<HBaseColumn<String>>. 
         * column: "state". 
         */
        public static final String STATE = (__ + ".state").intern();

        /**
         * Name of "zipCode" property. 
         * type: List<HBaseColumn<String>>. 
         * column: "zipCode". 
         */
        public static final String ZIP_CODE = (__ + ".zipCode").intern();

        /**
         * Name of "status" property. 
         * type: List<HBaseColumn<Integer>>. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: List<HBaseColumn<Timestamp>>. 
         * column: "lastUpdateTime". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: List<HBaseColumn<Timestamp>>. 
         * column: "createTime". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections
                .unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, TELEPHONE, CITY, STATE, ZIP_CODE, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(Arrays.asList("account_contact.id".intern(), "account_contact.accountId".intern(),
                "account_contact.telephone".intern(), "account_contact.city".intern(), "account_contact.state".intern(), "account_contact.zipCode".intern(),
                "account_contact.status".intern(), "account_contact.lastUpdateTime".intern(), "account_contact.createTime".intern()));
    }

    public static interface AccountDevicePNL {
        /**
         * Name of "AccountDevice" entity. 
         */
        public static final String __ = "AccountDevice".intern();

        /**
         * Name of "id" property. 
         * type: HBaseColumn<Long>. 
         * column: "id". 
         */
        public static final String ID = (__ + ".id").intern();

        /**
         * Name of "accountId" property. 
         * type: HBaseColumn<Long>. 
         * column: "accountId". 
         */
        public static final String ACCOUNT_ID = (__ + ".accountId").intern();

        /**
         * Name of "name" property. 
         * type: HBaseColumn<String>. 
         * column: "name". 
         */
        public static final String NAME = (__ + ".name").intern();

        /**
         * Name of "UDID" property. 
         * type: HBaseColumn<String>. 
         * column: "UDID". 
         */
        public static final String UDID = (__ + ".UDID").intern();

        /**
         * Name of "platform" property. 
         * type: HBaseColumn<String>. 
         * column: "platform". 
         */
        public static final String PLATFORM = (__ + ".platform").intern();

        /**
         * Name of "model" property. 
         * type: HBaseColumn<String>. 
         * column: "model". 
         */
        public static final String MODEL = (__ + ".model").intern();

        /**
         * Name of "manufacturer" property. 
         * type: HBaseColumn<String>. 
         * column: "manufacturer". 
         */
        public static final String MANUFACTURER = (__ + ".manufacturer").intern();

        /**
         * Name of "produceTime" property. 
         * type: HBaseColumn<Timestamp>. 
         * column: "produceTime". 
         */
        public static final String PRODUCE_TIME = (__ + ".produceTime").intern();

        /**
         * Name of "category" property. 
         * type: HBaseColumn<String>. 
         * column: "category". 
         */
        public static final String CATEGORY = (__ + ".category").intern();

        /**
         * Name of "description" property. 
         * type: HBaseColumn<String>. 
         * column: "description". 
         */
        public static final String DESCRIPTION = (__ + ".description").intern();

        /**
         * Name of "status" property. 
         * type: HBaseColumn<Integer>. 
         * column: "status". 
         */
        public static final String STATUS = (__ + ".status").intern();

        /**
         * Name of "lastUpdateTime" property. 
         * type: HBaseColumn<Timestamp>. 
         * column: "lastUpdateTime". 
         */
        public static final String LAST_UPDATE_TIME = (__ + ".lastUpdateTime").intern();

        /**
         * Name of "createTime" property. 
         * type: HBaseColumn<Timestamp>. 
         * column: "createTime". 
         */
        public static final String CREATE_TIME = (__ + ".createTime").intern();

        /**
         * Immutable property name list
         */
        public static final List<String> _PNL = Collections.unmodifiableList(Arrays.asList(ID, ACCOUNT_ID, NAME, UDID, PLATFORM, MODEL, MANUFACTURER,
                PRODUCE_TIME, CATEGORY, DESCRIPTION, STATUS, LAST_UPDATE_TIME, CREATE_TIME));

        /**
         * Immutable column name list
         */
        public static final List<String> _CNL = Collections.unmodifiableList(
                Arrays.asList("account_device.id".intern(), "account_device.accountId".intern(), "account_device.name".intern(), "account_device.UDID".intern(),
                        "account_device.platform".intern(), "account_device.model".intern(), "account_device.manufacturer".intern(),
                        "account_device.produceTime".intern(), "account_device.category".intern(), "account_device.description".intern(),
                        "account_device.status".intern(), "account_device.lastUpdateTime".intern(), "account_device.createTime".intern()));
    }

    public static final String ACCOUNT_ID = "accountId".intern();

    public static final String CATEGORY = "category".intern();

    public static final String CITY = "city".intern();

    public static final String CONTACT = "contact".intern();

    public static final String CREATE_TIME = "createTime".intern();

    public static final String DESCRIPTION = "description".intern();

    public static final String EMAIL_ADDRESS = "emailAddress".intern();

    public static final String FIRST_NAME = "firstName".intern();

    public static final String GUI = "gui".intern();

    public static final String ID = "id".intern();

    public static final String LAST_NAME = "lastName".intern();

    public static final String LAST_UPDATE_TIME = "lastUpdateTime".intern();

    public static final String MANUFACTURER = "manufacturer".intern();

    public static final String MIDDLE_NAME = "middleName".intern();

    public static final String MODEL = "model".intern();

    public static final String NAME = "name".intern();

    public static final String PLATFORM = "platform".intern();

    public static final String PRODUCE_TIME = "produceTime".intern();

    public static final String STATE = "state".intern();

    public static final String STATUS = "status".intern();

    public static final String STR_MAP = "strMap".intern();

    public static final String STR_SET = "strSet".intern();

    public static final String TELEPHONE = "telephone".intern();

    public static final String UDID = "UDID".intern();

    public static final String ZIP_CODE = "zipCode".intern();
}
