/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.noInherit;

import java.util.List;
import java.sql.Timestamp;
import java.util.Objects;
import com.landawn.abacus.annotation.Type;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Author {
    private long id;
    private String firstName;
    private String lastName;
    private Timestamp birthDay;
    private Contact contact;
    private List<Book> book;

    public Author() {
    }

    public Author(long id) {
        this();

        setId(id);
    }

    public Author(String firstName, String lastName, Timestamp birthDay, Contact contact, List<Book> book) {
        this();

        setFirstName(firstName);
        setLastName(lastName);
        setBirthDay(birthDay);
        setContact(contact);
        setBook(book);
    }

    public Author(long id, String firstName, String lastName, Timestamp birthDay, Contact contact, List<Book> book) {
        this();

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setBirthDay(birthDay);
        setContact(contact);
        setBook(book);
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public Author setId(long id) {
        this.id = id;

        return this;
    }

    @Type("String")
    public String getFirstName() {
        return firstName;
    }

    public Author setFirstName(String firstName) {
        this.firstName = firstName;

        return this;
    }

    @Type("String")
    public String getLastName() {
        return lastName;
    }

    public Author setLastName(String lastName) {
        this.lastName = lastName;

        return this;
    }

    @Type("Timestamp")
    public Timestamp getBirthDay() {
        return birthDay;
    }

    public Author setBirthDay(Timestamp birthDay) {
        this.birthDay = birthDay;

        return this;
    }

    @Type("com.landawn.abacus.entity.noInherit.Contact")
    public Contact getContact() {
        return contact;
    }

    public Author setContact(Contact contact) {
        this.contact = contact;

        return this;
    }

    @Type("List<com.landawn.abacus.entity.noInherit.Book>")
    public List<Book> getBook() {
        return book;
    }

    public Author setBook(List<Book> book) {
        this.book = book;

        return this;
    }

    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(id);
        h = 31 * h + Objects.hashCode(firstName);
        h = 31 * h + Objects.hashCode(lastName);
        h = 31 * h + Objects.hashCode(birthDay);
        h = 31 * h + Objects.hashCode(contact);
        h = 31 * h + Objects.hashCode(book);

        return h;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Author) {
            final Author other = (Author) obj;

            return Objects.equals(id, other.id) && Objects.equals(firstName, other.firstName) && Objects.equals(lastName, other.lastName)
                    && Objects.equals(birthDay, other.birthDay) && Objects.equals(contact, other.contact) && Objects.equals(book, other.book);
        }

        return false;
    }

    public String toString() {
        return "{id=" + Objects.toString(id) + ", firstName=" + Objects.toString(firstName) + ", lastName=" + Objects.toString(lastName) + ", birthDay="
                + Objects.toString(birthDay) + ", contact=" + Objects.toString(contact) + ", book=" + Objects.toString(book) + "}";
    }
}
