/*
 * Generated by Abacus.
 */
package com.landawn.abacus.entity.implDirty;

import java.util.Collection;
import java.util.Set;
import java.util.List;
import com.landawn.abacus.core.DirtyMarkerImpl;
import java.util.Objects;
import com.landawn.abacus.annotation.Id;
import com.landawn.abacus.annotation.Column;
import com.landawn.abacus.DirtyMarker;
import com.landawn.abacus.entity.implDirty.ImplDirtyPNL;
import javax.xml.bind.annotation.XmlTransient;
import com.landawn.abacus.annotation.Type;

/**
 * Generated by Abacus.
 * @version ${version}
 */
public class Book implements ImplDirtyPNL.BookPNL, DirtyMarker {
    private final DirtyMarkerImpl dirtyMarkerImpl = new DirtyMarkerImpl(__);

    @Id
    @Column("id")
    private long id;

    @Column("name")
    private String name;

    @Column("language")
    private String language;

    private List<Author> author;

    public Book() {
    }

    public Book(long id) {
        this();

        setId(id);
    }

    public Book(String name, String language, List<Author> author) {
        this();

        setName(name);
        setLanguage(language);
        setAuthor(author);
    }

    public Book(long id, String name, String language, List<Author> author) {
        this();

        setId(id);
        setName(name);
        setLanguage(language);
        setAuthor(author);
    }

    public String entityName() {
        return __;
    }

    @XmlTransient
    public boolean isDirty() {
        return dirtyMarkerImpl.isDirty() || (author == null ? false : dirtyMarkerImpl.isEntityDirty(author));
    }

    @XmlTransient
    public boolean isDirty(String propName) {
        return dirtyMarkerImpl.isDirty(propName);
    }

    public void markDirty(boolean isDirty) {
        dirtyMarkerImpl.markDirty(isDirty);

        if (author != null) {
            dirtyMarkerImpl.markEntityDirty(author, isDirty);
        }
    }

    public void markDirty(String propName, boolean isDirty) {
        dirtyMarkerImpl.markDirty(propName, isDirty);
    }

    public void markDirty(Collection<String> propNames, boolean isDirty) {
        dirtyMarkerImpl.markDirty(propNames, isDirty);
    }

    @XmlTransient
    public Set<String> signedPropNames() {
        return dirtyMarkerImpl.signedPropNames();
    }

    @XmlTransient
    public Set<String> dirtyPropNames() {
        return dirtyMarkerImpl.dirtyPropNames();
    }

    @XmlTransient
    public void freeze() {
        dirtyMarkerImpl.freeze();
    }

    @XmlTransient
    public boolean frozen() {
        return dirtyMarkerImpl.frozen();
    }

    @XmlTransient
    public long version() {
        return dirtyMarkerImpl.version();
    }

    @Type("long")
    public long getId() {
        return id;
    }

    public Book setId(long id) {
        dirtyMarkerImpl.setUpdatedPropName(ID);
        this.id = id;

        return this;
    }

    @Type("String")
    public String getName() {
        return name;
    }

    public Book setName(String name) {
        dirtyMarkerImpl.setUpdatedPropName(NAME);
        this.name = name;

        return this;
    }

    @Type("String")
    public String getLanguage() {
        return language;
    }

    public Book setLanguage(String language) {
        dirtyMarkerImpl.setUpdatedPropName(LANGUAGE);
        this.language = language;

        return this;
    }

    @Type("List<com.landawn.abacus.entity.implDirty.Author>")
    public List<Author> getAuthor() {
        return author;
    }

    public Book setAuthor(List<Author> author) {
        dirtyMarkerImpl.setUpdatedPropName(AUTHOR);
        this.author = author;

        return this;
    }

    public int hashCode() {
        int h = 17;
        h = 31 * h + Objects.hashCode(id);
        h = 31 * h + Objects.hashCode(name);
        h = 31 * h + Objects.hashCode(language);
        h = 31 * h + Objects.hashCode(author);

        return h;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof Book) {
            final Book other = (Book) obj;

            return Objects.equals(id, other.id) && Objects.equals(name, other.name) && Objects.equals(language, other.language)
                    && Objects.equals(author, other.author);
        }

        return false;
    }

    public String toString() {
        return "{id=" + Objects.toString(id) + ", name=" + Objects.toString(name) + ", language=" + Objects.toString(language) + ", author="
                + Objects.toString(author) + "}";
    }
}
